# Generated by Django 5.2 on 2025-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                ("is_markdown", models.BooleanField(default=True)),
                ("date_published", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
