# Generated by Django 5.2 on 2025-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="articles_pdfs/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
