# Generated by Django 5.2 on 2025-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_article_pdf_file_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.CharField(
                choices=[("grimoire", "The Grimoire"), ("mstag", "MSTAG")],
                default="mstag",
                max_length=20,
            ),
        ),
    ]
