# Generated by Django 5.2 on 2025-07-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Link to ResearchGate, Google Scholar, etc.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
