# Generated by Django 5.2 on 2025-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_article_external_url_article_linkedin_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
